Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine319"  # Updated to the latest stable version
  
    # Server VM Configuration
    config.vm.define "deddaraS" do |control|
      control.vm.hostname = "deddaraS"
      control.vm.network "private_network", ip: "192.168.60.110"
      control.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "deddaraS"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.memory = 1024
        v.cpus = 1
      end
      control.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-iface=eth1" K3S_TOKEN=hyinya K3S_KUBECONFIG_MODE="644" sh -
      SHELL
    end
  
    # Worker VM Configuration
    config.vm.define "deddaraSW" do |control|
      control.vm.hostname = "deddaraSW"
      control.vm.network "private_network", ip: "192.168.60.111"
      control.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "deddaraSW"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.memory = 1024
        v.cpus = 1
      end
      control.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --flannel-iface=eth1" K3S_URL=https://192.168.60.110:6443 K3S_TOKEN=hyinya sh -
      SHELL
    end
  end
  