Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"
    config.vm.synced_folder ".", "/vagrant", type: 'rsync'

    config.vm.define "deddaraS" do |control|
        control.vm.hostname = "deddaraS"
        control.vm.network "public_network", bridge: "wlp3s0"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "deddaraS"]
            v.memory = 8196
            v.cpus = 5
        end
        # control.vm.provision "shell", path: "./scripts/disk_prepare.sh"
        control.vm.provision "shell", path: "./scripts/script.sh"
    end
end