Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"
    config.vm.synced_folder ".", "/vagrant"

    config.vm.define "deddaraS" do |control|
        control.vm.hostname = "deddaraS"
        control.vm.network "public_network", bridge: "wlp3s0"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "deddaraS"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", path: "./scripts/script.sh"
    end
end
